# Generated by Django 6.0.7 on 2026-07-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetryQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_payload",
                    models.TextField(
                        help_text="Original TTN JSON string exactly as received from MQTT broker"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        help_text="UTC datetime when the message was originally received"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Retry"),
                            ("success", "Successfully Processed"),
                            ("failed", "Permanently Failed"),
                        ],
                        default="pending",
                        help_text="Current status: pending retry, successfully processed, or permanently failed",
                        max_length=10,
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of processing attempts (max 3)"
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of the last retry attempt",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message from the most recent processing attempt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this retry queue entry was created",
                    ),
                ),
            ],
            options={
                "verbose_name": "MQTT Retry Queue Entry",
                "verbose_name_plural": "MQTT Retry Queue Entries",
                "ordering": ["received_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "attempts"],
                        name="mqtt_client_status_be7adf_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="mqtt_client_receive_f050f9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="mqtt_client_created_a035ab_idx"
                    ),
                ],
            },
        ),
    ]
