# Generated by Django 6.0.7 on 2026-07-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField()),
                ("temperature", models.FloatField(help_text="°C")),
                ("humidity", models.FloatField(help_text="%")),
                ("pressure", models.FloatField(help_text="hPa")),
                ("wind_speed", models.FloatField(help_text="m/s")),
                ("wind_direction", models.FloatField(help_text="degrees, 0-360")),
                ("rainfall", models.FloatField(help_text="mm")),
                ("light_intensity", models.FloatField(help_text="lux")),
                ("battery", models.FloatField(help_text="%")),
                ("rssi", models.IntegerField(help_text="dBm")),
                ("snr", models.FloatField(help_text="dB")),
                ("raw_payload", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["-received_at"], name="weather_received_at_desc"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "received_at"), name="weather_reading_pk"
                    )
                ],
            },
        ),
    ]
